a=int(input("enter the 1'st number"))
b=int(input("enter the 2nd number"))
c=int(input("enter the 3rd number"))
d=int(input("enter the 4th number"))
e=complex(a,b)
f=complex(c,d)
print("addition",e+f)
print("substraction",e-f)
print("multiplication",e*f)
print("division",e/f)
